# Generated by Django 4.2.4 on 2024-01-10 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_response_date_added_alter_response_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
