# Generated by Django 5.0.1 on 2024-01-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0010_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advertising',
            field=models.CharField(choices=[('PC_300', '300 кр.'), ('P1_200', '200 кр.'), ('P11_200', '200 кр.')], max_length=50, null=True),
        ),
    ]
