# Generated by Django 5.0.1 on 2024-01-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0012_alter_order_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
